SiteCarrosDUB/Controllers/AlterarSenhaController.cs
using Microsoft.AspNetCore.Mvc;
using SiteCarrosDUB.Filters;
using SiteCarrosDUB.Helper;
using SiteCarrosDUB.Models;
using SiteCarrosDUB.Repositorios;
using static System.Runtime.InteropServices.JavaScript.JSType;

namespace SiteCarrosDUB.Controllers
{
    public class AlterarSenhaController : Controller
    {
        private readonly IUsuariosRepositorio _usuariosRepositorio;
        private readonly ISessao _sessao;
        public AlterarSenhaController(IUsuariosRepositorio usuariosRepositorio,
                                      ISessao sessao)
        {
            _usuariosRepositorio = usuariosRepositorio;
            _sessao = sessao;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Alterar(AlterarSenhaModel alterarSenhaModel)
        {
            try
            {             
                UsuariosModel usuarioLogado = _sessao.BuscarSessaoUsuario();
                alterarSenhaModel.Id = usuarioLogado.Id;

                if(ModelState.IsValid) 
                {                  
                    _usuariosRepositorio.AlterarSenha(alterarSenhaModel);
                    TempData["MensagemSucesso"] = "Senha alterada com sucesso!";
                    return View("Index", alterarSenhaModel);
                }

                TempData["MensagemErro"] = "Houve um erro ao tentar redefinir a senha, mais detalhes do erro";
                return View("Index", alterarSenhaModel);

            }
            catch (Exception erro)
            {
                TempData["MensagemErro"] = $"Houve um erro ao tentar redefinir a senha, mais detalhes do erro:{erro.Message}";
                return View("Index", alterarSenhaModel);
            }
        }
    }
}

SiteCarrosDUB/Views/AlterarSenha/Index.cshtml
@model AlterarSenhaModel
@{

}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
</head>
<body>
    <main>
        @if (TempData["MensagemSucesso"] != null)
        {
            <div class="alert alert-success" role="alert">
                <button type="button" class="btn btn-danger btn-sm close-alert" arial-label="Close">X</button>
                @TempData["MensagemSucesso"]
            </div>
        }
        @if (TempData["MensagemErro"] != null)
        {
            <div class="alert alert-danger" role="alert">
                <button type="button" class="btn btn-danger btn-sm close-alert" arial-label="Close">X</button>
                @TempData["MensagemErro"]
            </div>
        }
        <h1>Alterar Senha</h1>
        <form asp-controller="AlterarSenha" asp-action="Alterar" method="post">
            <div class="form-group">
                <label for="senhaAtual">Senha atual</label>
                <input type="password" class="form-control" asp-for="SenhaAtual" placeholder="Informe sua senha atual">
                @Html.ValidationMessageFor(x => x.SenhaAtual)
            </div>
            <div class="form-group">
                <label for="novaSenha">Nova Senha</label>
                <input type="password" class="form-control" asp-for="NovaSenha" placeholder="Informe a sua nova senha">
                @Html.ValidationMessageFor(x => x.NovaSenha)
            </div>
            <div class="form-group">
                <label for="confirmarSenha">Confirme a senha</label>
                <input type="password" class="form-control" asp-for="ConfirmarSenha" placeholder="Confirme sua nova senha">
                @Html.ValidationMessageFor(x => x.ConfirmarSenha)
            </div>
            <br />
            <nav class="botoes1">
                <button type="submit" class="btn btn-primary btn-block">Alterar</button>
                <a class="btn btn-danger" asp-controller="Home" asp-action="Index" role="button">Cancelar</a>
            </nav>
        </form>
    </main>
</body>
</html>