SiteCarrosDUB/Controllers/AcessoriosController.cs
using Microsoft.AspNetCore.Mvc;
using SiteCarrosDUB.Filters;
using SiteCarrosDUB.Models;
using SiteCarrosDUB.Repositorios;

namespace SiteCarrosDUB.Controllers
{
    [SessaoRestrita]
    public class AcessoriosController : Controller
    {
        private readonly IAcessoriosRepositorio _acessoriosRepositorio;
        public AcessoriosController(IAcessoriosRepositorio acessoriosRepositorio)
        {
            _acessoriosRepositorio = acessoriosRepositorio;
        }
        public IActionResult Index()
        {
            List<AcessoriosModel> acessorios = _acessoriosRepositorio.BuscarTodos();
            return View(acessorios);
        }
        public IActionResult Criar()
        {
            return View();
        }
        public IActionResult ApagarAcessorio(int id)
        {
            AcessoriosModel acessorios = _acessoriosRepositorio.ListarPorId(id);
            return View(acessorios);
        }
        public IActionResult Apagar(int id)
        {
            try
            {
                bool apagado = _acessoriosRepositorio.Apagar(id);
                if (apagado)
                {
                    TempData["MensagemSucesso"] = "Contato apagado com sucesso!";
                }
                else
                {
                    TempData["MensagemErro"] = "Houve um erro ao apagar o contato";
                }
                return RedirectToAction("Index");
            }
            catch (Exception erro)
            {
                TempData["MensagemErro"] = $"Houve um erro ao apagar o contato, mais detalhes do erro:{erro.Message}";
                return RedirectToAction("Index");
            }
        }
        public IActionResult Editar(int id)
        {
            AcessoriosModel acessorios = _acessoriosRepositorio.ListarPorId(id);
            return View(acessorios);
        }
        [HttpPost]
        public IActionResult Criar(AcessoriosModel acessoriosModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _acessoriosRepositorio.Adicionar(acessoriosModel);
                    TempData["MensagemSucesso"] = "Contato criado com sucesso!";
                    return RedirectToAction("Index");
                }
                return View(acessoriosModel);
            }
            catch (Exception erro)
            {
                TempData["MensagemErro"] = $"Não foi possivel cadastrar este contato, detalhes do erro:{erro.Message}";
                return RedirectToAction("Index");
            }
        }
        [HttpPost]
        public IActionResult Editar(AcessoriosModel acessoriosModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _acessoriosRepositorio.Atualizar(acessoriosModel);
                    TempData["MensagemSucesso"] = "Contato alterado com sucesso!";
                    return RedirectToAction("Index");
                }
                return View("Editar", acessoriosModel);
            }
            catch (Exception erro)
            {
                TempData["MensagemErro"] = $"Houve um erro ao alterar o contato, mais detalhes do erro:{erro.Message}";
                return RedirectToAction("Index");
            }
        }
    }
}

SiteCarrosDUB/Views/Acessorios/ApagarAcessorio.cshtml
@model AcessoriosModel

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
</head>
<body>
    <main>
        <h1>Realmente deseja apagar a peça (@Model.NomeDaPeca)?</h1>
        <nav class="botao-adicionar2">
            <a class="btn btn-primary" asp-action="Apagar" asp-controller="Acessorios" asp-route-id="@Model.Id" role="button">Confirmar</a>
            <a class="btn btn-danger" asp-action="Index" asp-controller="Acessorios" role="button">Cancelar</a>
        </nav>
    </main>
</body>
</html>

SiteCarrosDUB/Views/Acessorios/Criar.cshtml
@model AcessoriosModel
@{
}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
</head>
<body>
    <main>
        <h1>Cadastro de Peças</h1>
        <form asp-controller="Acessorios" asp-action="Criar" method="post">
            <div class="form-group">
                <label for="nomedapeca">Nome da Peça</label>
                <input type="text" class="form-control" asp-for="NomeDaPeca" placeholder="Digite o nome da peça">
                @Html.ValidationMessageFor(x => x.NomeDaPeca)
            </div>

            <div class="form-group">
                <label for="marca">Marca da Peça</label>
                <input type="text" class="form-control" asp-for="Marca" placeholder="Digite a marca da peça">
                @Html.ValidationMessageFor(x => x.Marca)
            </div>

            <div class="form-group">
                <label for="valor">Valor</label>
                <input type="text" class="form-control" asp-for="Valor" placeholder="Digite o valor da peça">
                @Html.ValidationMessageFor(x => x.Valor)
            </div>
            <br />
            <nav class="botoes1">
                <button type="submit" class="btn btn-primary btn-block">Adicionar</button>
                <a class="btn btn-danger btn-block" asp-controller="Acessorios" asp-action="Index" role="button">Voltar</a>
            </nav>
        </form>
    </main>
</body>
</html>

SiteCarrosDUB/Views/Acessorios/Editar.cshtml
@model AcessoriosModel
@{

}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
</head>
<body>
    <main>
        <h1>Editar Cadastro das Peças</h1>
        <form asp-controller="Acessorios" asp-action="Editar" method="post">
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label for="nomedapeca">Nome da Peça</label>
                <input type="text" asp-for="NomeDaPeca" class="form-control" placeholder="Digite o nome que deseja para alterar">
                @Html.ValidationMessageFor(x => x.NomeDaPeca)
            </div>
            <div class="form-group">
                <label for="marca">Marca da Peça</label>
                <input type="text" asp-for="Marca" class="form-control" placeholder="Digite o nome da marca que deseja para alterar">
                @Html.ValidationMessageFor(x => x.Marca)
            </div>
            <div class="form-group">
                <label for="valor">Valor da Peça</label>
                <input type="text" asp-for="Valor" class="form-control" placeholder="Digite o valor que deseja para alterar">
                @Html.ValidationMessageFor(x => x.Valor)
            </div>
            <br />
            <nav class="botoes1">
                <button type="submit" class="btn btn-primary btn-block">Editar</button>
                <a class="btn btn-danger" asp-controller="Acessorios" asp-action="Index" role="button">Cancelar</a>
            </nav>
        </form>
    </main>
</body>
</html>

SiteCarrosDUB/Views/Acessorios/Index.cshtml
@model List<AcessoriosModel>

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
</head>
<body>
    <main>
        @if (TempData["MensagemSucesso"] != null)
        {
            <div class="alert alert-success" role="alert">
                <button type="button" class="btn btn-danger btn-sm close-alert" arial-label="Close">X</button>
                @TempData["MensagemSucesso"]
            </div>
        }
        @if (TempData["MensagemErro"] != null)
        {
            <div class="alert alert-danger" role="alert">
                <button type="button" class="btn btn-danger btn-sm close-alert" arial-label="Close">X</button>
                @TempData["MensagemErro"]
            </div>
        }
        <nav class="botao-adicionar">
            <a class="btn btn-primary" role="button" asp-controller="Acessorios" asp-action="Criar">Adicionar uma nova peça</a>
        </nav>
        <h1>As Peças</h1>
        <div class="table-container">
            <table>
                <thead>
                    <tr>
                        <th scope="col">ID</th>
                        <th scope="col">Nome da Peça</th>
                        <th scope="col">Marca da Peça</th>
                        <th scope="col">Valor</th>
                        <th scope="col"></th>
                    </tr>
                </thead>
                <tbody>
                    @if (Model != null && Model.Any())
                    {
                        foreach (var acessorio in Model)
                        {
                            <tr>
                                <td>@acessorio.Id</td>
                                <td>@acessorio.NomeDaPeca</td>
                                <td>@acessorio.Marca</td>
                                <td>@acessorio.Valor</td>
                                <td>
                                    <a role="button" class="btn btn-primary" asp-route-id="@acessorio.Id" asp-controller="Acessorios" asp-action="Editar">Editar</a>
                                    <a role="button" class="btn btn-danger" asp-route-id="@acessorio.Id" asp-controller="Acessorios" asp-action="ApagarAcessorio">Apagar</a>
                                </td>
                            </tr>
                        }
                    }
                    else
                    {
                        <tr class="add"><td valign="top" colspan="5">Nenhum usuario encontrado</td></tr>
                    }
                </tbody>
            </table>
        </div>
    </main>
</body>
</html>